### ISSUE TITLE
最后增加引用element-ui css‘报错’

### ISSUE THREAD

**Issue by zhouheng2005** [showonne/vue2-example#13]
import Element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
Vue.use(Element)
![Uploading 1495590017(1).jpg…]()

**Comment by zhouheng2005** [comment]
![2](https://user-images.githubusercontent.com/30518490/29054836-24d16bb8-7c2b-11e7-9415-64b26ceae428.jpg)
图片上传不了郁闷

**Comment by zhouheng2005** [comment]
就是出现这种提示错误说什么渲染的没有定义

**Comment by showonne** [comment]
把webpack.config.js里的resolveLoader属性删除。
