### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by Ittit** [showonne/vue2-example#3]
在不启动路由之前的教程都可以直线实现，但是在单页应用进行修改时会出现页面报错，页面直接都没有了，即便clone源码也是跑不起来。

**Comment by shijiansu** [comment]
教程里面有些省略的步骤, 建议你下源码过去比较一下. 跑不起来的原因有可能是开发环境问题. 最好把错误贴出来让大家参考一下吧.

**Comment by 5265liu** [comment]
应该是你的app没注册成功吧仔细检查下，我也遇到了这个问题；

**Comment by showonne** [comment]
没有错误描述没办法知道什么问题，最新的例子已经可用。
