### ISSUE TITLE
请教关于本地全局命令webpack和vue-cli的版本问题

### ISSUE THREAD

**Issue by shijiansu** [showonne/vue2-example#7]
谢谢你的教程!
你好, 我按https://aotu.io/notes/2016/10/13/vue2/上述的操作, 在本地安装webpack和vue-cli, 执行命令
```
npm install webpack -g
npm install vue-cli -g
```
安装后的版本为
webpack@1.14.0
vue-cli@2.8.0
然后执行vue命令去创建目录,
`vue init webpack-simple 某个项目名字`
安装完寻找项目目录下的package.json文件, 发现在devDependencies中,这两个版本如下
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0"
上述的webpack版本的配置规范与原教程有冲突, 请问你开发该项目的时候, 其本地的webpack和vue-cli的版本各是什么呢? 
谢谢!

**Comment by showonne** [comment]
因为package.json里的版本号也不是锁死的，所以这个不用太纠结，基本上主版本号一致就可以了。
