### ISSUE TITLE
是否有计划升级webpack的版本?

### ISSUE THREAD

**Issue by shijiansu** [showonne/vue2-example#8]
想知道你是否有计划升级webpack的版本及其配置文件呢?
升级的理由如下,
1. "webpack": "^2.2.0"相对于原来的beta的版本号, 更加稳定;
2. 现在按教程安装后新建的vue项目为webpack 2.2.0, 其配置规范有所修改, 例如在webpack.config.js中的loader, 需要加上-loader
谢谢!

**Comment by showonne** [comment]
已升级。
