### ISSUE TITLE
webpack -color -progress执行提示错误

### ISSUE THREAD

**Issue by shijiansu** [showonne/vue2-example#9]
参考https://aotu.io/notes/2016/10/13/vue2/上面执行
`webpack -color -progress`
执行提示错误:
Unknown arguments: c, o, l, r, g, e, s
其webpack版本为2.1.0-beta.22.
如果单独执行webpack, 或者npm run build是可以通过的.
谢谢!

**Comment by showonne** [comment]
应该是`--`而不是`-`
